### ISSUE TITLE
Set default input to cuffnorm format FPKM matrix

### ISSUE THREAD

**Issue by hilldr** [hilldr/gene_retriever#1]
The intended use of **Gene Retriever** is the analysis of output FPKM data from the [Cufflinks software suite](https://github.com/cole-trapnell-lab/cufflinks). Therefore, by default the function should be able to produce data tables and plots from CuffNorm output files without preceding manipulation in R. The following tasks are necessary to implement this feature:
- [x] Reformat CuffNorm output within the function for optimal Gene Retriever implementation

**Comment by hilldr** [comment]
**Gene Retriever** is intended for use by individuals with little to no experience using R. As such, output files should be formatted for viewing and manipulation in common spreadsheet software.

- Change retrieved gene expression table export from CSV to XLS format

**Comment by hilldr** [comment]
Here's a quick way to format the input from norm_out.

``` Rscript
data1 <- read.table("./norm_out/genes.count_table",header=TRUE,sep="\t")
attr.table <- read.table("./norm_out/genes.attr_table",header=TRUE,sep="\t")
data1$gene_short_name <- attr.table$gene_short_name
```

**Comment by hilldr** [comment]
Another thing to keep in mind: the names of the files produced in the cuffnorm output directory will not change, but the directory name itself is specified by the user. I always use "norm_out" but in theory it could be anything. Perhaps the user should specify the directory (and not the specific files) in the function call?
- [ ] User specifies directory containing CfuffNorm output files

**Comment by sthodla** [comment]
Wouldn't the user run the function in the directory containing the file? If not, then I would think we would need to know the path to that directory and not just the directory name itself. I agree about not having to specify the specific files.

**Comment by hilldr** [comment]
Good point. Maybe the default cuffnorm directory should be the working directory 

``` shell
./
```

unless the user specifies another path. I typically have the cuffnorm output in its own (sub-)subdirectory just to keep things organized, for example 

``` shell
./DATA/norm_out
```

Where all the raw data for a project is in 

``` shell
./DATA
```

And the cuffnorm output is just part of that.

**Comment by sthodla** [comment]
Ok, that would work

**Comment by hilldr** [comment]
- [x] Change function option "wd=" to "dir=" to avoid confusion in cases where the cuffnorm output is in a different directory from the working directory
