### ISSUE TITLE
Merge output format with master

### ISSUE THREAD

**Issue by hilldr** [hilldr/gene_retriever#16]
Consolidate 'gene retriever" into a single function with user-specified plot device.

The plot device option could take the form of a boolean operator, e.g.

``` R
gene_retriever(pdf=TRUE,...)
```

With TRUE resulting in PDF output and FALSE resulting in PNG output. The data retrieval portion of the code should be shared, with the 'branch' applying only to the device opened for plotting. Another component of this is user specification of height and width. Both should have consistent units within the gene_retriever() function call (i.e. pixels or inches). Note that the default units for a pdf device are inches and the default units for a png device are pixels. Units can be specified for either plot device using "units="

**Comment by sthodla** [comment]
Done. There should be no problems, but let me know if you run into any.
