### ISSUE TITLE
Add pheatmap output

### ISSUE THREAD

**Issue by hilldr** [hilldr/gene_retriever#17]
``` R
library(pheatmap)
pheatmap(as.matrix(plot.data),scale="row",clustering_method="average",color=colorRampPalette(rev(brewer.pal(n = 7, name ="RdYlBu")))(300),main="Cluster 3",border_color="black",show_rownames=FALSE,fontsize=12,filename="./DATA/group3subset.png")
dev.off()
```

**Comment by sthodla** [comment]
I'm having some trouble getting this to work, it seems like the as.matrix function converts all numeric variables into characters. I've tried other things like turning data_for into a matrix outside the function call, I've used the data.matrix function and some other alternatives but none have worked so far.
Here is the error message I get:

```
Error in x - m : non-numeric argument to binary operator
In addition: There were 50 or more warnings (use warnings() to see the first 50)
```

and the warnings are all like this:

```
1: In mean.default(newX[, i], ...) :
  argument is not numeric or logical: returning NA
```

This is how the code concerning the heatmap looked originally:

```
 if (heatmap == TRUE) {
        library(pheatmap)
        png(file="heat.png", width=w, height=h, units="in", res=144)
        heat<-pheatmap(as.matrix(data_for),scale="row",clustering_method="average",color=colorRampPalette(rev(brewer.pal(n = 7, name ="RdYlBu")))(300),main="Cluster3",border_color="black",show_rownames=FALSE,fontsize=12,filename="heat.png")
        print(heat)
    }
```

But I am still changing things to see if I can get it to work. Maybe you know someway to fix this off the top of your head?

**Comment by hilldr** [comment]
Thanks for posting this. Does data_for contain a column of gene names? These should be set as the row names and then the column should be removed i.e.

``` R
rownames(data_for) <- data_for$gene_short_name
gsn <- grep("gene_short_name", colnames(data_for)
data_for <- data_for[,-gsn]
```

I think that might do the trick, but I'm not sure where to add it to your script. The error message indicates that you are submitting non-numeric data to as.matrix() so I think this is probably the gene names.

**Comment by sthodla** [comment]
I was adding these at the very end of gene_retriever as a if statement like so:

```
if (heatmap == TRUE) {
        library(pheatmap)
        rownames(data_for) <- data_for$gene_short_name
        gsn <- grep("gene_short_name", colnames(data_for))
        data_for <- data_for[,-gsn]
        png(file="heat.png", width=w, height=h, units="in", res=144)
        heat<-pheatmap(as.matrix(data_for),scale="row",clustering_method="average",color=colorRampPalette(rev(brewer.pal(n = 7, name ="RdYlBu")))(300),main="Cluster3",border_color="black",show_rownames=FALSE,fontsize=12,filename="heat.png")
        print(heat)
    }
```

I added the code you have above after the library(pheatmap) statement and get the following error:

```
Error in rev(brewer.pal(n = 7, name = "RdYlBu")) : 
  could not find function "brewer.pal"
In addition: Warning messages:
1: In min(x, na.rm = T) : no non-missing arguments to min; returning Inf
2: In max(x, na.rm = T) : no non-missing arguments to max; returning -Inf
```

I'll see what I can find online to fix these.
