### ISSUE TITLE
Add XLSX table output format

### ISSUE THREAD

**Issue by hilldr** [hilldr/gene_retriever#2]
**Gene Retriever** is intended for use by individuals with little to no experience using R. As such, output files should be formatted for viewing and manipulation in common spreadsheet software.
- [ ] Change retrieved gene expression table export from CSV to XLSX format
- [ ] Should GR generate both CSV and XLSX? Should there be a use option to specify one or the other?

**Comment by sthodla** [comment]
I think .xlsx should be good enough, the one thing .csv can do that .xlsx can't is be opened in a text editor.

**Comment by hilldr** [comment]
``` R
library(xlsx)
write.xlsx(mydata, "c:/mydata.xlsx") 
```

From http://www.statmethods.net/input/exportingdata.html

**Comment by hilldr** [comment]
Decided to abandon XLSX output for the following reasons
- XLSX requires JAVA development tools installation, which may be a barrier to use
- CSV files are opened in excel by default and easily converted to XLSX using 'Save as' feature

Will reopen this issue if a case can be made the XLSX format output offers any functional advantage over a CSV file opened in Excel.
